#:schema https://mise.jdx.dev/schema/mise.json

[tools]
node = "20.15.0"
python = "3.12.4"
ruby = "3.2.2"
"npm:eslint_d" = "14.0.3"
usage = "latest"
"npm:typescript" = "latest"
"cargo:ubi-cli" = "latest"
"ubi:simeji/jid" = "latest"

[env]
_.file = ["~/.env"]
# MISE_ENV_FILE = ".env"

[settings]
experimental = true
status.show_env = true
status.show_tools = true
